# The configuration for the builder is in YAML format. You can use
# https://www.yamllint.com/ to make sure that your configuration
# file is correctly formatted.

# First we need to define the source files to build. Please list
# all sources in the same family. These are expected to be in the
# sources/ directory, so all paths should be relative to that
# directory.
sources:
  - KolbiSans-Regular.glyphs
  - KolbiSans-Italic.glyphs
  - KolbiSans-Medium.glyphs
  - KolbiSans-MediumItalic.glyphs
  - KolbiSans-SemiBold.glyphs
  - KolbiSans-SemiBoldItalic.glyphs
  - KolbiSans-Bold.glyphs
  - KolbiSans-BoldItalic.glyphs

# You don't have to supply the family name, but builds are slightly
# faster if you do.
familyName: "Kolbi Sans"

# outputDir: ../fonts
# vfDir: $outputDir/variable
# ttDir: $outputDir/ttf
# otDir: $outputDir/otf
# woffDir: $outputDir/webfonts

# The following entries, which are either "true" or "false"
# determine which targets to build.
buildOTF: false

# stat table configuration
stat:
  KolbiSans[wght].ttf:
  - name: Weight
    tag: wght
    values:
    - name: Regular
      value: 400
      linkedValue: 700
      flags: 2
    - name: Medium
      value: 500
    - name: SemiBold
      value: 600
    - name: Bold
      value: 700
  - name: Italic
    tag: ital
    values:
    - name: Roman
      value: 0
      linkedValue: 1
      flags: 2

  KolbiSans-Italic[wght].ttf:
  - name: Weight
    tag: wght
    values:
    - name: Regular
      value: 400
      linkedValue: 700
      flags: 2
    - name: Medium
      value: 500
    - name: SemiBold
      value: 600
    - name: Bold
      value: 700
  - name: Italic
    tag: ital
    values:
    - name: Italic
      value: 1
